version: '3.3'
services:
  client:
    build: .
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/var/lib/mysql
    command:
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --skip-character-set-client-handshake
      --secure-file-priv=''
      --local-infile=1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
